[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [string] $CabinetRoot,
    [ValidateSet('kinect', 'webcam', 'steamvr')]
    [string] $Backend = 'kinect',
    [string] $WindowSize,
    [string] $WindowPosition,
    [string] $OutputName,
    [switch] $Force
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$CabinetRoot = (Resolve-Path -LiteralPath $CabinetRoot).Path
if ([string]::IsNullOrWhiteSpace($OutputName)) {
    $OutputName = "launch_anygear_$Backend.bat"
}
if ([IO.Path]::GetFileName($OutputName) -ne $OutputName) {
    throw '-OutputName must be a file name, not a path.'
}

foreach ($Pair in @(
    @{ Name = 'WindowSize'; Value = $WindowSize; NonZero = $true },
    @{ Name = 'WindowPosition'; Value = $WindowPosition; NonZero = $false })) {
    if ([string]::IsNullOrWhiteSpace($Pair.Value)) { continue }
    $Parts = $Pair.Value.Split(',')
    [uint32] $First = 0
    [uint32] $Second = 0
    if ($Parts.Count -ne 2 -or
        -not [uint32]::TryParse($Parts[0], [ref]$First) -or
        -not [uint32]::TryParse($Parts[1], [ref]$Second) -or
        ($Pair.NonZero -and ($First -eq 0 -or $Second -eq 0))) {
        throw "-$($Pair.Name) must be two unsigned integers separated by a comma."
    }
}

$PluginName = "dance_around_anygear_$Backend.dll"
$RequiredFiles = @(
    (Join-Path $CabinetRoot 'game\dancearound.exe'),
    (Join-Path $CabinetRoot 'modules\kamunity.dll'),
    (Join-Path $CabinetRoot 'modules\execexe.dll'),
    (Join-Path $CabinetRoot $PluginName)
)
if ($Backend -eq 'webcam') {
    $RequiredFiles += @(
        (Join-Path $CabinetRoot 'dance_around_anygear_webcam\libmediapipe.dll'),
        (Join-Path $CabinetRoot 'dance_around_anygear_webcam\pose_landmarker_lite.task')
    )
}
if ($Backend -eq 'steamvr') {
    $RequiredFiles += @(
        (Join-Path $CabinetRoot 'dance_around_anygear_steamvr\openvr_api.dll'),
        (Join-Path $CabinetRoot 'dance_around_anygear_steamvr\LICENSE.openvr.txt')
    )
}
foreach ($required in $RequiredFiles) {
    if (-not (Test-Path -LiteralPath $required -PathType Leaf)) {
        throw "Required launch file not found: $required"
    }
}

$OutputPath = Join-Path $CabinetRoot $OutputName
if ((Test-Path -LiteralPath $OutputPath) -and -not $Force) {
    throw "Launcher already exists: $OutputPath (use -Force to replace it)"
}

$WindowArguments = ''
if (-not [string]::IsNullOrWhiteSpace($WindowSize)) {
    $WindowArguments += " -windowsize $WindowSize"
}
if (-not [string]::IsNullOrWhiteSpace($WindowPosition)) {
    $WindowArguments += " -windowpos $WindowPosition"
}

$Bat = @"
@echo off
rem Generated by dance-around-anygear. This file only starts Spice; backend
rem configuration and VP4U diagnostics live inside $PluginName.
setlocal EnableExtensions
pushd "%~dp0"
"game\dancearound.exe" -runas user -modules modules -ea -cardio -w$WindowArguments -keyboardnav -loglevel info -k $PluginName %*
set "RESULT=%ERRORLEVEL%"
popd
exit /b %RESULT%
"@
[IO.File]::WriteAllText(
    $OutputPath,
    [regex]::Replace($Bat, "`r?`n", "`r`n"),
    [Text.Encoding]::ASCII)

Write-Host "[OK] Launcher generated (not executed): $OutputPath"
Write-Host "     Runtime customization required from the user: -k $PluginName"
if ($WindowArguments) {
    Write-Host "     Window override: -w$WindowArguments"
}
